title: Site
email: andy@goodscary.com
description: ""
url: "https://madeofpeoplepodcast.com"

plugins:
  - jekyll-seo-tag

include:
  - _redirects

exclude:
  - gulpfile.js
  - javascripts/
  - node_modules/
  - package.json
  - package-lock.json
  - README.md
  - scss/
  - yarn.lock

podcast:
  title: "Made of People"
  description: "A series of interviews with people who think wider than the technology that they use."
  summary: "A series of interviews with people who think wider than the technology that they use. All software is made of people after all. Started as a result of Brighton Ruby not being an “in person” thing in 2020."
  url: /podcast.xml # podcast xml url
  author: Andy Croll
  email: andy@goodscary.com
  logo: "/images/show-artwork.jpg"
  language: en # iso639-2
  category: Technology # help.apple.com/itc/podcasts_connect/#/itc9267a2f12
  subcategory: "Society & Culture"
  type: episodic # episodic | serial
  # explicit: "yes" | default: "no"
  # block: # "yes" | default: "no"
  # copyright: # defaults to author
